---
# file: oracle-java/tasks/main.yml
#
# tasks file
#

- name: check host environment
  include: check_environment.yml

## include OS family specific variables

- name: include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "../defaults/{{ ansible_distribution | lower }}.yml"
    - "../defaults/{{ ansible_os_family | lower }}.yml"


## include OS family specific task file


- name: if debian, include family specific task file
  include: "debian/main.yml"
  when: ansible_os_family | lower == 'debian'